### ISSUE TITLE
<hostname>:-1 in Logs

### ISSUE THREAD

**Issue by aaron-brown** [budjb/http-requests#15] opened 2019-01-02 21:50 UTC
Please note that in some cases when using the ```http-requests``` library, you may encounter something like this:

```
https://example.com:-1/path/to/resource
```

When you expect something like this:

```
https://example.com:80/path/to/resource
```

Or, in other words, the ```port``` is shown as ```:-1```.

You may try to investigate why this value is ```:-1``` for a long time. Stop. It is a red herring. Double-check your URI / URL and ensure it is correct. In 100% of cases where this occurred, so far, it has been an issue with either the hostname, or the path being incorrect, and it was determined that the appearance of the ```:-1``` in the port _is only a logging anomaly_ and is just a misdirecting symptom of a different problem.

**Comment by aaron-brown** [comment] 2019-01-02 21:51
@budjb: Please add any info you would like to this and close. It is just informaitonal in case people search for this particular behavior, to save them some grief.

**Comment by budjb** [comment] 2020-05-21 17:26
I know this was an issue before, but I can't reproduce using JDK 8u181. I've even looked at the code in the `URI` class and it explicitly does not add the port if it is set to `-1` (which is the default). I'm going to go ahead and close this for now, and we can address if we can reproduce it.

**Closed as completed by budjb** 2020-05-21 17:26 UTC
